[2021-11-15 20:04:01,779] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: covid_ingestion.process_BE_cases manual__2021-11-15T20:03:59.401335+00:00 [queued]>
[2021-11-15 20:04:01,790] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: covid_ingestion.process_BE_cases manual__2021-11-15T20:03:59.401335+00:00 [queued]>
[2021-11-15 20:04:01,791] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-15 20:04:01,791] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-11-15 20:04:01,791] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-15 20:04:01,807] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): process_BE_cases> on 2021-11-15 20:03:59.401335+00:00
[2021-11-15 20:04:01,812] {standard_task_runner.py:52} INFO - Started process 899 to run task
[2021-11-15 20:04:01,815] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'covid_ingestion', 'process_BE_cases', 'manual__2021-11-15T20:03:59.401335+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/covid_ingestion.py', '--cfg-path', '/tmp/tmp8hnu1fh3', '--error-file', '/tmp/tmp9sgkjvl4']
[2021-11-15 20:04:01,815] {standard_task_runner.py:77} INFO - Job 48: Subtask process_BE_cases
[2021-11-15 20:04:01,851] {logging_mixin.py:109} INFO - Running <TaskInstance: covid_ingestion.process_BE_cases manual__2021-11-15T20:03:59.401335+00:00 [running]> on host e693d79b64a2
[2021-11-15 20:04:01,894] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=covid_ingestion
AIRFLOW_CTX_TASK_ID=process_BE_cases
AIRFLOW_CTX_EXECUTION_DATE=2021-11-15T20:03:59.401335+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-15T20:03:59.401335+00:00
[2021-11-15 20:04:01,910] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas/core/series.py:1056: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cacher_needs_updating = self._check_is_chained_assignment_possible()

[2021-11-15 20:04:01,912] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas/core/indexing.py:1724: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer_missing(indexer, value)

[2021-11-15 20:04:01,944] {python.py:152} INFO - Done. Returned value was: {'date': '2021-11-15', 'deaths': 0.0, 'infections': 1.0, 'canton': 'BE'}
[2021-11-15 20:04:01,965] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=covid_ingestion, task_id=process_BE_cases, execution_date=20211115T200359, start_date=20211115T200401, end_date=20211115T200401
[2021-11-15 20:04:01,986] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-15 20:04:02,017] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
