[2021-11-15 11:10:55,839] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: covid_ingestion.process_BE manual__2021-11-15T11:10:51.550789+00:00 [queued]>
[2021-11-15 11:10:55,854] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: covid_ingestion.process_BE manual__2021-11-15T11:10:51.550789+00:00 [queued]>
[2021-11-15 11:10:55,854] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-15 11:10:55,854] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-11-15 11:10:55,854] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-15 11:10:55,876] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): process_BE> on 2021-11-15 11:10:51.550789+00:00
[2021-11-15 11:10:55,880] {standard_task_runner.py:52} INFO - Started process 5796 to run task
[2021-11-15 11:10:55,884] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'covid_ingestion', 'process_BE', 'manual__2021-11-15T11:10:51.550789+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/covid_ingestion.py', '--cfg-path', '/tmp/tmpzk63j94x', '--error-file', '/tmp/tmp6w60kkpa']
[2021-11-15 11:10:55,885] {standard_task_runner.py:77} INFO - Job 118: Subtask process_BE
[2021-11-15 11:10:55,930] {logging_mixin.py:109} INFO - Running <TaskInstance: covid_ingestion.process_BE manual__2021-11-15T11:10:51.550789+00:00 [running]> on host 6f9154c92b39
[2021-11-15 11:10:55,979] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=covid_ingestion
AIRFLOW_CTX_TASK_ID=process_BE
AIRFLOW_CTX_EXECUTION_DATE=2021-11-15T11:10:51.550789+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-15T11:10:51.550789+00:00
[2021-11-15 11:10:56,027] {logging_mixin.py:109} INFO -            date time  ... ncumul_deceased                                source
624  2021-11-15  NaN  ...          1186.0  https://covid-kennzahlen.apps.be.ch/

[1 rows x 11 columns]
[2021-11-15 11:10:56,030] {warnings.py:110} WARNING - /opt/***/dags/covid_ingestion.py:89: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cases_today['infections'] = cases_today['ncumul_conf'] - cases_yesterday['ncumul_conf']

[2021-11-15 11:10:56,031] {warnings.py:110} WARNING - /opt/***/dags/covid_ingestion.py:90: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cases_today['deaths'] = cases_today['ncumul_deceased'] - cases_yesterday['ncumul_deceased']

[2021-11-15 11:10:56,032] {python.py:152} INFO - Done. Returned value was: {'deaths_amount': 624    0.0
Name: deaths, dtype: float64, 'municipality_postal_code': '', 'place': '', 'canton': 'BE', 'infections': 624    0.0
Name: infections, dtype: float64, 'test_positive': 591    485
Name: positive_tests, dtype: int64, 'test_negative': 591   NaN
Name: negative_tests, dtype: float64, 'positivity_rate': 591    8.76
Name: positivity_rate, dtype: float64}
[2021-11-15 11:10:56,037] {xcom.py:334} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2021-11-15 11:10:56,037] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1517, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2262, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 100, in set
    value = XCom.serialize_value(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 331, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Series is not JSON serializable
[2021-11-15 11:10:56,054] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=covid_ingestion, task_id=process_BE, execution_date=20211115T111051, start_date=20211115T111055, end_date=20211115T111056
[2021-11-15 11:10:56,071] {standard_task_runner.py:91} ERROR - Failed to execute job 118 for task process_BE
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1517, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2262, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 100, in set
    value = XCom.serialize_value(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 331, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Series is not JSON serializable
[2021-11-15 11:10:56,096] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-11-15 11:10:56,130] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
