[2021-11-15 19:58:36,533] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: covid_ingestion.ingest_to_dwh manual__2021-11-15T19:58:32.279193+00:00 [queued]>
[2021-11-15 19:58:36,544] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: covid_ingestion.ingest_to_dwh manual__2021-11-15T19:58:32.279193+00:00 [queued]>
[2021-11-15 19:58:36,544] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-15 19:58:36,544] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-11-15 19:58:36,545] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-15 19:58:36,560] {taskinstance.py:1262} INFO - Executing <Task(PostgresOperator): ingest_to_dwh> on 2021-11-15 19:58:32.279193+00:00
[2021-11-15 19:58:36,564] {standard_task_runner.py:52} INFO - Started process 680 to run task
[2021-11-15 19:58:36,567] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'covid_ingestion', 'ingest_to_dwh', 'manual__2021-11-15T19:58:32.279193+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/covid_ingestion.py', '--cfg-path', '/tmp/tmpqr1ras3q', '--error-file', '/tmp/tmpfpqb1s9c']
[2021-11-15 19:58:36,568] {standard_task_runner.py:77} INFO - Job 40: Subtask ingest_to_dwh
[2021-11-15 19:58:36,601] {logging_mixin.py:109} INFO - Running <TaskInstance: covid_ingestion.ingest_to_dwh manual__2021-11-15T19:58:32.279193+00:00 [running]> on host e693d79b64a2
[2021-11-15 19:58:36,642] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=covid_ingestion
AIRFLOW_CTX_TASK_ID=ingest_to_dwh
AIRFLOW_CTX_EXECUTION_DATE=2021-11-15T19:58:32.279193+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-15T19:58:32.279193+00:00
[2021-11-15 19:58:36,649] {base.py:79} INFO - Using connection to: id: postgres_dwh. Host: postgres-dwh, Port: 5432, Schema: None, Login: ***, Password: ***, extra: {}
[2021-11-15 19:58:36,652] {dbapi.py:225} INFO - Running statement: INSERT INTO dim_canton VALUES (1, 'BE', NOW());, parameters: None
[2021-11-15 19:58:36,653] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 69, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "dim_canton_pkey"
DETAIL:  Key (canton_key)=(1) already exists.

[2021-11-15 19:58:36,667] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=covid_ingestion, task_id=ingest_to_dwh, execution_date=20211115T195832, start_date=20211115T195836, end_date=20211115T195836
[2021-11-15 19:58:36,681] {standard_task_runner.py:91} ERROR - Failed to execute job 40 for task ingest_to_dwh
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 69, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 205, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 229, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "dim_canton_pkey"
DETAIL:  Key (canton_key)=(1) already exists.

[2021-11-15 19:58:36,699] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-11-15 19:58:36,725] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
