[2021-11-15 18:15:38,151] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: covid_ingestion.process_BE_cases manual__2021-11-15T18:15:08.767609+00:00 [queued]>
[2021-11-15 18:15:38,165] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: covid_ingestion.process_BE_cases manual__2021-11-15T18:15:08.767609+00:00 [queued]>
[2021-11-15 18:15:38,165] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-15 18:15:38,165] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-11-15 18:15:38,165] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-15 18:15:38,183] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): process_BE_cases> on 2021-11-15 18:15:08.767609+00:00
[2021-11-15 18:15:38,188] {standard_task_runner.py:52} INFO - Started process 2569 to run task
[2021-11-15 18:15:38,191] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'covid_ingestion', 'process_BE_cases', 'manual__2021-11-15T18:15:08.767609+00:00', '--job-id', '179', '--raw', '--subdir', 'DAGS_FOLDER/covid_ingestion.py', '--cfg-path', '/tmp/tmp9nvou_71', '--error-file', '/tmp/tmpt8izkvxf']
[2021-11-15 18:15:38,192] {standard_task_runner.py:77} INFO - Job 179: Subtask process_BE_cases
[2021-11-15 18:15:38,230] {logging_mixin.py:109} INFO - Running <TaskInstance: covid_ingestion.process_BE_cases manual__2021-11-15T18:15:08.767609+00:00 [running]> on host 6f9154c92b39
[2021-11-15 18:15:38,301] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=covid_ingestion
AIRFLOW_CTX_TASK_ID=process_BE_cases
AIRFLOW_CTX_EXECUTION_DATE=2021-11-15T18:15:08.767609+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-15T18:15:08.767609+00:00
[2021-11-15 18:15:38,325] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas/core/series.py:1056: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cacher_needs_updating = self._check_is_chained_assignment_possible()

[2021-11-15 18:15:38,327] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas/core/indexing.py:1724: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer_missing(indexer, value)

[2021-11-15 18:15:38,328] {python.py:152} INFO - Done. Returned value was: {'date': '2021-11-15', 'deaths_amount': 0.0, 'infections': 1.0, 'canton': 'BE'}
[2021-11-15 18:15:38,358] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=covid_ingestion, task_id=process_BE_cases, execution_date=20211115T181508, start_date=20211115T181538, end_date=20211115T181538
[2021-11-15 18:15:38,403] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-15 18:15:38,436] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
