[2021-11-15 18:52:14,684] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: covid_ingestion.process_BE_cases manual__2021-11-15T18:51:56.861387+00:00 [queued]>
[2021-11-15 18:52:14,697] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: covid_ingestion.process_BE_cases manual__2021-11-15T18:51:56.861387+00:00 [queued]>
[2021-11-15 18:52:14,698] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-15 18:52:14,698] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-11-15 18:52:14,698] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-15 18:52:14,716] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): process_BE_cases> on 2021-11-15 18:51:56.861387+00:00
[2021-11-15 18:52:14,720] {standard_task_runner.py:52} INFO - Started process 4022 to run task
[2021-11-15 18:52:14,723] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'covid_ingestion', 'process_BE_cases', 'manual__2021-11-15T18:51:56.861387+00:00', '--job-id', '194', '--raw', '--subdir', 'DAGS_FOLDER/covid_ingestion.py', '--cfg-path', '/tmp/tmpqpo2bbqn', '--error-file', '/tmp/tmpph1usm5w']
[2021-11-15 18:52:14,724] {standard_task_runner.py:77} INFO - Job 194: Subtask process_BE_cases
[2021-11-15 18:52:14,762] {logging_mixin.py:109} INFO - Running <TaskInstance: covid_ingestion.process_BE_cases manual__2021-11-15T18:51:56.861387+00:00 [running]> on host 6f9154c92b39
[2021-11-15 18:52:14,809] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=covid_ingestion
AIRFLOW_CTX_TASK_ID=process_BE_cases
AIRFLOW_CTX_EXECUTION_DATE=2021-11-15T18:51:56.861387+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-15T18:51:56.861387+00:00
[2021-11-15 18:52:14,827] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas/core/series.py:1056: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cacher_needs_updating = self._check_is_chained_assignment_possible()

[2021-11-15 18:52:14,829] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas/core/indexing.py:1724: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer_missing(indexer, value)

[2021-11-15 18:52:14,830] {python.py:152} INFO - Done. Returned value was: {'date': '2021-11-15', 'deaths_amount': 0.0, 'infections': 1.0, 'canton': 'BE'}
[2021-11-15 18:52:14,850] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=covid_ingestion, task_id=process_BE_cases, execution_date=20211115T185156, start_date=20211115T185214, end_date=20211115T185214
[2021-11-15 18:52:14,895] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-15 18:52:14,930] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
